name: deploy-container
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    # paths:
    #   - "packages/container/**" // ACTIONS RUN ONLY IF CHANGES ARE MADE INSIDE CONTAINER FOLDER
defaults:
  run:
    working-directory: packages/container
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          ASW_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
